/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controlador;

/**
 *
 * @author Andrés Fernández Pereira
 */
public class Frameppal extends javax.swing.JFrame {
    private Controlador controlador;

    /**
     * Creates new form Frameppal
     */
    public Frameppal(Controlador controlador) {
        initComponents();
        this.controlador = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProvincia = new javax.swing.JButton();
        jProfesions = new javax.swing.JButton();
        jNovoTraballador = new javax.swing.JButton();
        jTraballadoresDisponibles = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicacións multixanela Dáilogos");

        jProvincia.setText("Provincias");
        jProvincia.setToolTipText("provincias");
        jProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProvinciaActionPerformed(evt);
            }
        });

        jProfesions.setText("Profesións");
        jProfesions.setToolTipText("profesións");
        jProfesions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProfesionsActionPerformed(evt);
            }
        });

        jNovoTraballador.setText("Novo Traballador");
        jNovoTraballador.setToolTipText("Traballador");
        jNovoTraballador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNovoTraballadorActionPerformed(evt);
            }
        });

        jTraballadoresDisponibles.setText("Traballadores Disponibles");
        jTraballadoresDisponibles.setToolTipText("Traballadores");
        jTraballadoresDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTraballadoresDisponiblesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProvincia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProfesions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNovoTraballador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTraballadoresDisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jProvincia)
                .addGap(28, 28, 28)
                .addComponent(jProfesions)
                .addGap(26, 26, 26)
                .addComponent(jNovoTraballador)
                .addGap(18, 18, 18)
                .addComponent(jTraballadoresDisponibles)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Métodos para abrir las ventanas de cada uno de ellas
    private void jProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProvinciaActionPerformed
        controlador.abrirVistaXestionProvincias();
    }//GEN-LAST:event_jProvinciaActionPerformed

    private void jProfesionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProfesionsActionPerformed
        controlador.abrirVistaXestionProfesions();
    }//GEN-LAST:event_jProfesionsActionPerformed

    private void jNovoTraballadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNovoTraballadorActionPerformed
        controlador.abrirVistaAltaTraballador();
    }//GEN-LAST:event_jNovoTraballadorActionPerformed

    private void jTraballadoresDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTraballadoresDisponiblesActionPerformed
        controlador.abrirVistaTraballadoresDisponibles();
    }//GEN-LAST:event_jTraballadoresDisponiblesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frameppal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frameppal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frameppal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frameppal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Controlador controlador = new Controlador();
                Frameppal frame = new Frameppal(controlador);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jNovoTraballador;
    private javax.swing.JButton jProfesions;
    private javax.swing.JButton jProvincia;
    private javax.swing.JButton jTraballadoresDisponibles;
    // End of variables declaration//GEN-END:variables
}
