/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controlador;
import javax.swing.JOptionPane;

/**
 *
 * @author Andrés Fernández Pereira
 */
public class VistaXestionProfesions extends javax.swing.JFrame {
private Controlador controlador;
    
    /**
     * Creates new form VistaProfesions
     */
    public VistaXestionProfesions(Controlador controlador) {
        initComponents();
        this.controlador = controlador;
         actualizarTextoProfesions(); // Cargar las profesiones al inicio
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLProfesions = new javax.swing.JLabel();
        jLNova = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTprofesion = new javax.swing.JTextArea();
        jTEngadir = new javax.swing.JTextField();
        jBEliminar = new javax.swing.JButton();
        jBEngadir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Xestións de profesións");

        jLProfesions.setText("Profesións");

        jLNova.setText("Nova");

        jTprofesion.setColumns(20);
        jTprofesion.setRows(5);
        jTprofesion.setText("Carpintero\nElectricista\nPintor");
        jScrollPane1.setViewportView(jTprofesion);

        jBEliminar.setText("Eliminar profesións");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBEngadir.setText("Engadir profesións");
        jBEngadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEngadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLProfesions)
                    .addComponent(jLNova))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jTEngadir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBEngadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLProfesions)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEliminar))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNova)
                    .addComponent(jTEngadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEngadir))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Método para añadir los las profesiones
    private void jBEngadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEngadirActionPerformed
         String novaProfesion = jTEngadir.getText().trim();
        if (!novaProfesion.isEmpty()) {
            // Llamar al método del controlador para añadir la profesión
            controlador.engadirProfesion(novaProfesion);
            actualizarTextoProfesions();
        } else {
            JOptionPane.showMessageDialog(this, "Debe ingresar unha profesión válida.");
        }
        //Llama al método limpiar campos
        limpiarCampos();
    }//GEN-LAST:event_jBEngadirActionPerformed

    //Método para limpiar los campos
    private void limpiarCampos() {
            jTEngadir.setText("");           
    }
    
    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        String profesion = jTprofesion.getSelectedText();
        if (profesion != null) {
            // Llamar al método del controlador para eliminar la profesión
            controlador.eliminarProfesion(profesion);
            actualizarTextoProfesions();
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione unha profesión para eliminar.");
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    
    private void actualizarTextoProfesions() {
        StringBuilder profesionsTexto = new StringBuilder();
        for (String profesion : controlador.getProfesions()) {
            profesionsTexto.append(profesion).append("\n");
        }
        jTprofesion.setText(profesionsTexto.toString());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaXestionProfesions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaXestionProfesions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaXestionProfesions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaXestionProfesions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Controlador controlador = new Controlador(false);
                new VistaXestionProfesions(controlador).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBEngadir;
    private javax.swing.JLabel jLNova;
    private javax.swing.JLabel jLProfesions;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTEngadir;
    private javax.swing.JTextArea jTprofesion;
    // End of variables declaration//GEN-END:variables

    
}
