/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controlador;
import javax.swing.JOptionPane;

/**
 *
 * @author Andrés Fernández Pereira
 */
public class VistaAltaTraballador extends javax.swing.JFrame {
       private Controlador controlador;
    /**
     * Creates new form VistaProvincias
     */
    public VistaAltaTraballador(Controlador controlador) {
        initComponents();
        this.controlador = controlador;
        actualizarComboProvincias(); // Cargar las provincias al inicio
        actualizarTextoProfesions(); // Cargar las profesiones al inicio
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLDni = new javax.swing.JLabel();
        jLNome = new javax.swing.JLabel();
        jLApelido1 = new javax.swing.JLabel();
        jLApellido2 = new javax.swing.JLabel();
        jLProvincia = new javax.swing.JLabel();
        jLProfesion = new javax.swing.JLabel();
        jTDni = new javax.swing.JTextField();
        jTNome = new javax.swing.JTextField();
        jTApellido1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaProfesion = new javax.swing.JTextArea();
        jAlta = new javax.swing.JButton();
        jTApellido2 = new javax.swing.JTextField();
        jComboProvincia = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta Traballador");

        jLDni.setText("DNI");

        jLNome.setText("Nome");

        jLApelido1.setText("Apellido1");

        jLApellido2.setText("Apellido2");

        jLProvincia.setText("Provincia");

        jLProfesion.setText("Profesión");

        jTextAreaProfesion.setColumns(20);
        jTextAreaProfesion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaProfesion);

        jAlta.setText("Alta");
        jAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLDni)
                            .addComponent(jLNome)
                            .addComponent(jLProvincia)
                            .addComponent(jLApellido2)
                            .addComponent(jLApelido1)
                            .addComponent(jLProfesion))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                            .addComponent(jTDni)
                            .addComponent(jTNome)
                            .addComponent(jTApellido1)
                            .addComponent(jTApellido2)
                            .addComponent(jComboProvincia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDni)
                    .addComponent(jTDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNome)
                    .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLApelido1)
                    .addComponent(jTApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLApellido2)
                    .addComponent(jTApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLProvincia)
                    .addComponent(jComboProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLProfesion))
                .addGap(28, 28, 28)
                .addComponent(jAlta)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Método para dar de alata un trabajador
    private void jAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAltaActionPerformed
     // Recoger datos del formulario
    String dni = jTDni.getText().trim();
    String nome = jTNome.getText().trim();
    String apelido1 = jTApellido1.getText().trim();
    String apelido2 = jTApellido2.getText().trim();
    String provincia = (String) jComboProvincia.getSelectedItem();
    String profesion = jTextAreaProfesion.getSelectedText(); // Obtener la profesión seleccionada

    // Validar que todos los campos estén completos y que se haya seleccionado una profesión
    if (dni.isEmpty() || nome.isEmpty() || apelido1.isEmpty() || apelido2.isEmpty() || provincia.isEmpty() || profesion == null || profesion.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios y debe seleccionar una profesión.", "Error", JOptionPane.ERROR_MESSAGE);
    } else {
        // Llamar al método del controlador para añadir al trabajador
        controlador.engadirTraballador(dni, nome, apelido1, apelido2, provincia, profesion);
        JOptionPane.showMessageDialog(this, "Traballador engadido correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        // Limpiar los campos
        limpiarCampos();
    }//GEN-LAST:event_jAltaActionPerformed
    }
    
    //Método para limpiar los campos
    private void limpiarCampos() {
            jTDni.setText("");
            jTNome.setText("");
            jTApellido1.setText("");
            jTApellido2.setText("");
            jComboProvincia.setSelectedIndex(0);
            
    }
    
    //Método para cargar los campos de la ventana Xestion Provincias a la venta Alta Traballador
     private void actualizarComboProvincias() {
        jComboProvincia.removeAllItems();
        for (String provincia : controlador.getProvincias()) {
            jComboProvincia.addItem(provincia);
        }
    }
     
     //Método para cargar los campos de la ventana Xestion Profesións a la venta Alta Traballador
     private void actualizarTextoProfesions() {
      StringBuilder profesionsTexto = new StringBuilder();
      for (String profesion : controlador.getProfesions()) {
        profesionsTexto.append(profesion).append("\n");
      }
        jTextAreaProfesion.setText(profesionsTexto.toString());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAltaTraballador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAltaTraballador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAltaTraballador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAltaTraballador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               Controlador controlador = new Controlador(); // No abrir Frameppal
                new VistaAltaTraballador(controlador).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAlta;
    private javax.swing.JComboBox<String> jComboProvincia;
    private javax.swing.JLabel jLApelido1;
    private javax.swing.JLabel jLApellido2;
    private javax.swing.JLabel jLDni;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLProfesion;
    private javax.swing.JLabel jLProvincia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTApellido1;
    private javax.swing.JTextField jTApellido2;
    private javax.swing.JTextField jTDni;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextArea jTextAreaProfesion;
    // End of variables declaration//GEN-END:variables
}
