/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controlador;
import javax.swing.JOptionPane;

/**
 *
 * @author Andrés Fernández Pereira
 */
public class VistaXestionProvincias extends javax.swing.JFrame {
        private Controlador controlador;
    /**
     * Creates new form VistaAltaTraballador
     */
    public VistaXestionProvincias(Controlador controlador) {
        initComponents();
        this.controlador = controlador;
        actualizarComboProvincias(); // Cargar las provincias al inicio
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLProvicnia = new javax.swing.JLabel();
        jLNova = new javax.swing.JLabel();
        jComboProvincia = new javax.swing.JComboBox<>();
        jTEngadir = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jEngadir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Xestión de Provincias");

        jLProvicnia.setText("Provincias");

        jLNova.setText("Nova");

        jComboProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lugo", "Pontevedra", "Coruña", "Ourense" }));

        jTEngadir.setToolTipText("N");

        jButton1.setText("Eliminar Provincia");
        jButton1.setToolTipText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jEngadir.setText("Engadir provincia");
        jEngadir.setToolTipText("Engadir");
        jEngadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEngadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLProvicnia)
                    .addComponent(jLNova))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboProvincia, 0, 259, Short.MAX_VALUE)
                    .addComponent(jTEngadir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jEngadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLProvicnia)
                    .addComponent(jComboProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNova)
                    .addComponent(jTEngadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEngadir))
                .addContainerGap(199, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Método para añadir provinicas
    private void jEngadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEngadirActionPerformed
        String novaProvincia = jTEngadir.getText().trim();
        if (!novaProvincia.isEmpty()) {
            // Llamar al método del controlador para engadir la provincia
            controlador.engadirProvincia(novaProvincia);
            actualizarComboProvincias();
        } else {
            JOptionPane.showMessageDialog(this, "Debe ingresar unha provincia válida.");
        }
        
        limpiarCampos();
    }//GEN-LAST:event_jEngadirActionPerformed

    //Método para actualizar la lista de provincias
     private void actualizarComboProvincias() {
        jComboProvincia.removeAllItems();
        for (String provincia : controlador.getProvincias()) {
            jComboProvincia.addItem(provincia);
        }
     }
     
     //Método para limpiar los campos
       private void limpiarCampos() {
            jTEngadir.setText("");
                    
    }
       
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String provincia = (String) jComboProvincia.getSelectedItem();
        if (provincia != null) {
            // Llamar al método del controlador para eliminar la provincia
            controlador.eliminarProvincia(provincia);
            //Actualiza la lista de provincias una vez eliminado
            actualizarComboProvincias();
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione unha provincia para eliminar.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaXestionProvincias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaXestionProvincias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaXestionProvincias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaXestionProvincias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Controlador controlador = new Controlador(false);
                new VistaXestionProvincias(controlador).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboProvincia;
    private javax.swing.JButton jEngadir;
    private javax.swing.JLabel jLNova;
    private javax.swing.JLabel jLProvicnia;
    private javax.swing.JTextField jTEngadir;
    // End of variables declaration//GEN-END:variables

}
