/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.util.Calendar;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author Andrés Fernández Pereira
 */
public class VistaFechas extends javax.swing.JFrame {

    /**
     * Creates new form VistaFechas
     */
    public VistaFechas() {
        initComponents();
        addMenuFechas(); // Agregar el menú "Fechas" después de la inicialización de componentes
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú fechas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
   private void addMenuFechas() {
        // Crear barra de menú
        JMenuBar menuBar = new JMenuBar();
        
        // Crear menú "Fechas"
        JMenu menuFechas = new JMenu("Fechas");
        
        // Crear ítems del menú "Fechas"
        JMenuItem menuItemFechaActual = new JMenuItem("Fecha Actual");
        JMenuItem menuItemSeleccionarFecha = new JMenuItem("Seleccionar Fecha");
        JMenuItem menuItemDiferenciaFechas = new JMenuItem("Calcular Diferencia de Fechas");
        
        // Agregar ítems al menú "Fechas"
        menuFechas.add(menuItemFechaActual);
        menuFechas.add(menuItemSeleccionarFecha);
        menuFechas.add(menuItemDiferenciaFechas);
        
        // Agregar menú "Fechas" a la barra de menú
        menuBar.add(menuFechas);
        
        // Establecer la barra de menú
        setJMenuBar(menuBar);
        
        // Acción para "Fecha Actual"
        menuItemFechaActual.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                String fechaActual = sdf.format(new Date());
                JOptionPane.showMessageDialog(null, "La fecha actual es: " + fechaActual);
            }
        });
        
        // Acción para "Seleccionar Fecha"
        menuItemSeleccionarFecha.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                SpinnerDateModel model = new SpinnerDateModel();
                JSpinner spinner = new JSpinner(model);
                JSpinner.DateEditor editor = new JSpinner.DateEditor(spinner, "dd/MM/yyyy");
                spinner.setEditor(editor);
                
                int result = JOptionPane.showConfirmDialog(null, spinner, "Seleccionar Fecha", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
                if (result == JOptionPane.OK_OPTION) {
                    Date selectedDate = (Date) spinner.getValue();
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                    JOptionPane.showMessageDialog(null, "Fecha seleccionada: " + sdf.format(selectedDate));
                }
            }
        });
        
        // Acción para "Calcular Diferencia de Fechas"
        menuItemDiferenciaFechas.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                JTextField startDateField = new JTextField(10);
                JTextField endDateField = new JTextField(10);
                JPanel panel = new JPanel();
                panel.add(new JLabel("Fecha inicio (dd/MM/yyyy):"));
                panel.add(startDateField);
                panel.add(new JLabel("Fecha fin (dd/MM/yyyy):"));
                panel.add(endDateField);
                
                int result = JOptionPane.showConfirmDialog(null, panel, "Calcular Diferencia de Fechas", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
                if (result == JOptionPane.OK_OPTION) {
                    try {
                        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                        Date startDate = sdf.parse(startDateField.getText());
                        Date endDate = sdf.parse(endDateField.getText());
                        long diff = endDate.getTime() - startDate.getTime();
                        long diffDays = diff / (1000 * 60 * 60 * 24);
                        JOptionPane.showMessageDialog(null, "Diferencia en días: " + diffDays);
                    } catch (ParseException e) {
                        JOptionPane.showMessageDialog(null, "Formato de fecha incorrecto.");
                    }
                }
            }
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaFechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaFechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaFechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaFechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaFechas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
