/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tutorialandres;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author a13andresfp
 */
public class PracticaCardLayout extends javax.swing.JFrame {

    /**
     * Creates new form PracticaLayout
     */
    public PracticaCardLayout() {
        //initComponents();
       
        JFrame frame = new JFrame("Ejemplo de cardLayout");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(400, 300); // Tamaño de la ventana
        
        //Crear el cardLayaout
        CardLayout cardLayout = new CardLayout();
        JPanel cardPanel = new JPanel(cardLayout); // Panel principal
        
        //Crear dos paneles para agregar al cardLayaout
        JPanel panel1 = new JPanel();
        panel1.setBackground(Color.MAGENTA);
        panel1.add(new JLabel("Rexistro de Usuario"));
        
        JPanel panel2 = new JPanel();
        panel2.setBackground(Color.ORANGE);
        panel2.add(new JLabel("Inicio de sesión"));
        
        //Agregar los paneles al contenedor del CardLayout
        cardPanel.add(panel1, "Rexistro de usuario");
        cardPanel.add(panel2, "Inicio de Sesión");
        
        //Crear los botones para cambiar entre panales
        JButton button1 = new JButton("Mostrar de usuario");
        JButton button2 = new JButton("Mostrar Inicio de sesión");
        
        //Agregar ActionListeners para los botones
        button1.addActionListener((ActionEvent e) -> {
            cardLayout.show(cardPanel, "Rexistro de usuario");
    });
        
          //Agregar ActionListeners para los botones
        button2.addActionListener((ActionEvent e) -> {
            cardLayout.show(cardPanel, "Inicio de Sesión");
    });
    
    //Crear un panel para los botones
    JPanel buttonPanel = new JPanel();
    buttonPanel.add(button1);
    buttonPanel.add(button2);
    
    //Agregar los paneles al frame
    frame.setLayout(new BorderLayout());
    frame.add(cardPanel, BorderLayout.CENTER);
    frame.add(buttonPanel, BorderLayout.SOUTH);
    
    //Mostrar la ventana
    frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PracticaCardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PracticaCardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PracticaCardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PracticaCardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PracticaCardLayout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
