/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author david
 */
public class VistaAbrirArchivo extends javax.swing.JDialog {

    /**
     * Creates new form vistaArchivo
     */
    public VistaAbrirArchivo(java.awt.Frame parent, boolean modal) {
        super(parent, false);
        File f;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreArchivo = new javax.swing.JLabel();
        lblRutaArchivo = new javax.swing.JLabel();
        lblNobreFichero = new javax.swing.JLabel();
        lblRutaFichero = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taFichero = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        taInfo = new javax.swing.JTextArea();
        btnAbriJFC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JFileChooser");
        setSize(new java.awt.Dimension(600, 600));

        lblNobreFichero.setText("Nombre:");

        lblRutaFichero.setText("Ruta:");

        taFichero.setColumns(20);
        taFichero.setRows(5);
        jScrollPane1.setViewportView(taFichero);

        taInfo.setColumns(20);
        taInfo.setRows(5);
        taInfo.setText("JFileChooser nos permite trabajar con ficheros. Para visualizarlo usamos su método \nshowOpenDialog(this), cuando seleccionamos el archivo deseado, lo agregamos a \nun objeto de tipo File por medio del método getSelectedFile().\nEn nuestro ejemplo recorremos el archivo y lo almacenamos en un String.\n\nEl resultado de este método es un entero que devolverá lo que el usuario \nhaya elegido, pudiendo ser:\n\nJFileChooser.CANCEL_OPTION: si el usuario pulsa Cancelar.\nJFileChooser.APPROVE_OPTION: si el usuario elige un fichero y pulsa el botón Aceptar.\nJFileChooser.ERROR_OPTION: si ocurre un error.");
        taInfo.setEnabled(false);
        jScrollPane2.setViewportView(taInfo);

        btnAbriJFC.setText("Abrir JFC");
        btnAbriJFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbriJFCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(btnAbriJFC))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNobreFichero)
                                    .addComponent(lblRutaFichero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAbriJFC)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNobreFichero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombreArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRutaFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbriJFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbriJFCActionPerformed
        JFileChooser jfc = new JFileChooser();
        /*Si queremos hacer un filtro en la selección de archivos haremos:*/
        jfc.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Tipo de arhivos","txt", "doc", "html","java");
        jfc.addChoosableFileFilter(filter);
    // visualizamos y controlamos que botón pulsa en selección
        int seleccion = jfc.showOpenDialog(this);
    // si pulsa el boton aceptar=> selección =0, cancel=> selección =1:
        if (seleccion == JFileChooser.APPROVE_OPTION) { //Si el usuario ha pulsado la opción Aceptar
            File fichero = jfc.getSelectedFile(); //Guardamos en la variable fichero el archivo seleccionado
            
            //podemos utilizar los métodos para ver info que necesitemos.
            lblNombreArchivo.setText(fichero.getName());
            lblRutaArchivo.setText(fichero.getAbsolutePath());

            //llamamos al método para visualizar el archivo en el TextArea
            taFichero.setText(verArchivo(fichero));
        }
    }//GEN-LAST:event_btnAbriJFCActionPerformed

    private String verArchivo(File file) {
        String aux = "";
        String texto = "";
        try {
            //recorremos el archivo, lo leemos para plasmarlo en el area de texto

            if (file != null) {
                FileReader archivoLeer = new FileReader(file);
                BufferedReader lee = new BufferedReader(archivoLeer);
                while ((aux = lee.readLine()) != null) {
                    texto += aux + "\n";
                }
                lee.close();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex + ""
                    + "\nNo se ha encontrado el archivo",
                    "ADVERTENCIA!!!", JOptionPane.WARNING_MESSAGE);
        }
        return texto;//El texto se almacena en el JTextArea

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAbrirArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAbrirArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAbrirArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAbrirArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VistaAbrirArchivo dialog = new VistaAbrirArchivo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbriJFC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNobreFichero;
    private javax.swing.JLabel lblNombreArchivo;
    private javax.swing.JLabel lblRutaArchivo;
    private javax.swing.JLabel lblRutaFichero;
    private javax.swing.JTextArea taFichero;
    private javax.swing.JTextArea taInfo;
    // End of variables declaration//GEN-END:variables
}
