/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import vista.GuardarArchivo;
import vista.VistaArchivo;
import vista.VistaColores;
import vista.VistaFechas;
import vista.VistaJCalendar;

/**
 *
 * @author Andrés Fernández Pereira
 */
public class Frameppal extends javax.swing.JFrame {

    /**
     * Creates new form Frameppal
     */
    public Frameppal() {
        initComponents();
        startClock();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        FechaActual = new javax.swing.JLabel();
        HoraActual = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuFile = new javax.swing.JMenuItem();
        jGuardar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuColor = new javax.swing.JMenuItem();
        menuFechas = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jVistaCalendar = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");

        FechaActual.setText("Fecha");
        FechaActual.setToolTipText("FechaActual");

        HoraActual.setText("Hora");
        HoraActual.setToolTipText("HoraActual");

        menuArchivo.setText("Archivo");
        menuArchivo.setToolTipText("Archivo");
        menuArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArchivoActionPerformed(evt);
            }
        });

        menuFile.setText("Selecciona Archivo");
        menuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFileActionPerformed(evt);
            }
        });
        menuArchivo.add(menuFile);

        jGuardar.setText("Guardar Archivo");
        jGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGuardarActionPerformed(evt);
            }
        });
        menuArchivo.add(jGuardar);

        jMenuBar1.add(menuArchivo);

        jMenu2.setText("colores");
        jMenu2.setToolTipText("Colores");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        menuColor.setText("Elegir color");
        menuColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuColorActionPerformed(evt);
            }
        });
        jMenu2.add(menuColor);

        jMenuBar1.add(jMenu2);

        menuFechas.setText("Fechas");
        menuFechas.setToolTipText("fechas");

        jMenuItem1.setText("Ventana Fechas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuFechas.add(jMenuItem1);

        jMenuBar1.add(menuFechas);

        jVistaCalendar.setText("Calendario");

        jMenuItem4.setText("Ventana Calendario");
        jMenuItem4.setToolTipText("Ventana");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jVistaCalendar.add(jMenuItem4);

        jMenuBar1.add(jVistaCalendar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(FechaActual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(HoraActual)
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FechaActual)
                    .addComponent(HoraActual))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
     
// TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    //Llamar la venta vista de colores
    private void menuColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuColorActionPerformed
        VistaColores vc = new VistaColores(this, false);
        vc.setVisible(true);    }//GEN-LAST:event_menuColorActionPerformed

    private void menuArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArchivoActionPerformed
         
    }//GEN-LAST:event_menuArchivoActionPerformed

    //Llamar a la ventana Vista Menú fechas
    private void menuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileActionPerformed
        VistaArchivo va= new VistaArchivo(this, true);
        va.setVisible(true);
    }//GEN-LAST:event_menuFileActionPerformed

    //Llamar la Vista guardar archivo
    private void jGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGuardarActionPerformed
         GuardarArchivo guardarArchivo = new GuardarArchivo();
          guardarArchivo.setVisible(true);
    }//GEN-LAST:event_jGuardarActionPerformed

    //Llamar a la vista Menu Fechas
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        VistaFechas vistaFechas = new VistaFechas();
        vistaFechas.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        VistaJCalendar vistaJCalendar = new VistaJCalendar();
        vistaJCalendar.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void startClock() {
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
                FechaActual.setText(dateFormat.format(now));
                HoraActual.setText(timeFormat.format(now));
            }
        });
        timer.start();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frameppal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frameppal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frameppal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frameppal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frameppal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FechaActual;
    private javax.swing.JLabel HoraActual;
    private javax.swing.JMenuItem jGuardar;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu jVistaCalendar;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuColor;
    private javax.swing.JMenu menuFechas;
    private javax.swing.JMenuItem menuFile;
    // End of variables declaration//GEN-END:variables

    
}
