/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.toedter.calendar.JDateChooser;
import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author Andrés Fernández Pereira
 */
public class VistaJCalendar extends javax.swing.JFrame {
    JDateChooser dateChooser;

    /**
     * Creates new form vistaJCalendar
     */
    public VistaJCalendar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jToolBar = new javax.swing.JToolBar();
        jFuente = new javax.swing.JButton();
        jColor = new javax.swing.JButton();
        jLabelFuente = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar.setRollover(true);

        jFuente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        jFuente.setToolTipText("Lupa");
        jFuente.setFocusable(false);
        jFuente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jFuente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jFuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFuenteActionPerformed(evt);
            }
        });
        jToolBar.add(jFuente);

        jColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario.png"))); // NOI18N
        jColor.setToolTipText("Calendario");
        jColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jColorActionPerformed(evt);
            }
        });

        jLabelFuente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelFuente.setText("Fuente");
        jLabelFuente.setToolTipText("Cambio Fuente");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFuente, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jColor)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addComponent(jLabelFuente)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Método para cuando puslses e
    private void jColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jColorActionPerformed
    // Abre el JColorChooser para seleccionar un color
    java.awt.Color newColor = javax.swing.JColorChooser.showDialog(this, "Seleccione un color", java.awt.Color.BLACK);
    if (newColor != null) {
        // Cambia el color de la imagen del calendario
        try {
            BufferedImage img = ImageIO.read(getClass().getResource("/imagenes/calendario.png"));
            BufferedImage newImg = changeImageColor(img, newColor);
            jColor.setIcon(new ImageIcon(newImg));

            // Muestra un mensaje con el color seleccionado
            JOptionPane.showMessageDialog(this, "Color seleccionado: " + newColor.toString());
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "No se pudo cargar la imagen.");
        }
    }
    }//GEN-LAST:event_jColorActionPerformed

    private void jFuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFuenteActionPerformed
        // Abre el diálogo para seleccionar una fuente
    String[] fonts = java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames();
    String selectedFont = (String) JOptionPane.showInputDialog(this, "Elija una fuente", "Seleccionar Fuente",
            JOptionPane.PLAIN_MESSAGE, null, fonts, fonts[0]);
    if (selectedFont != null) {
        java.awt.Font newFont = new java.awt.Font(selectedFont, java.awt.Font.PLAIN, 12);

        // Aquí puedes cambiar el color de la fuente del JLabel jLabelFuente
        jLabelFuente.setFont(newFont);

        // Muestra un mensaje con la fuente seleccionada
        JOptionPane.showMessageDialog(this, "Fuente seleccionada: " + selectedFont);
    }
    }//GEN-LAST:event_jFuenteActionPerformed

    // Método para cambiar el color de una imagen
private BufferedImage changeImageColor(BufferedImage img, Color newColor) {
    BufferedImage newImg = new BufferedImage(img.getWidth(), img.getHeight(), BufferedImage.TYPE_INT_ARGB);
    Graphics2D g = newImg.createGraphics();
    g.drawImage(img, 0, 0, null);
    g.setComposite(AlphaComposite.SrcAtop);
    g.setColor(newColor);
    g.fillRect(0, 0, img.getWidth(), img.getHeight());
    g.dispose();
    return newImg;
}

    private void addMenuFechas() {
    // Crear barra de menú
    JMenuBar menuBar = new JMenuBar();

    // Crear menú "Fechas"
    JMenu menuFechas = new JMenu("Fechas");

    // Crear ítems del menú "Fechas" con iconos
    JMenuItem menuItemFechaActual = new JMenuItem("Fecha Actual", new ImageIcon(getClass().getResource("/imagenes/calendario.png")));
    JMenuItem menuItemSeleccionarFecha = new JMenuItem("Seleccionar Fecha", new ImageIcon(getClass().getResource("/imagenes/calendario.png")));
    JMenuItem menuItemDiferenciaFechas = new JMenuItem("Calcular Diferencia de Fechas", new ImageIcon(getClass().getResource("/imagenes/calendario.png")));
    JMenuItem insertarFecha = new JMenuItem("Insertar Fecha", new ImageIcon(getClass().getResource("/imagenes/calendario.png")));

    // Agregar ítems al menú "Fechas"
    menuFechas.add(menuItemFechaActual);
    menuFechas.add(menuItemSeleccionarFecha);
    menuFechas.add(menuItemDiferenciaFechas);
    menuFechas.add(insertarFecha);

    // Agregar menú "Fechas" a la barra de menú
    menuBar.add(menuFechas);

    // Establecer la barra de menú
    setJMenuBar(menuBar);

    // Acción para "Fecha Actual"
    menuItemFechaActual.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String fechaActual = sdf.format(new Date());
            JOptionPane.showMessageDialog(null, "La fecha actual es: " + fechaActual);
        }
    });

    // Acción para "Seleccionar Fecha"
    menuItemSeleccionarFecha.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            SpinnerDateModel model = new SpinnerDateModel();
            JSpinner spinner = new JSpinner(model);
            JSpinner.DateEditor editor = new JSpinner.DateEditor(spinner, "dd/MM/yyyy");
            spinner.setEditor(editor);

            int result = JOptionPane.showConfirmDialog(null, spinner, "Seleccionar Fecha", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (result == JOptionPane.OK_OPTION) {
                Date selectedDate = (Date) spinner.getValue();
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                JOptionPane.showMessageDialog(null, "Fecha seleccionada: " + sdf.format(selectedDate));
            }
        }
    });

    // Acción para "Calcular Diferencia de Fechas"
    menuItemDiferenciaFechas.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            JTextField startDateField = new JTextField(10);
            JTextField endDateField = new JTextField(10);
            JPanel panel = new JPanel();
            panel.add(new JLabel("Fecha inicio (dd/MM/yyyy):"));
            panel.add(startDateField);
            panel.add(new JLabel("Fecha fin (dd/MM/yyyy):"));
            panel.add(endDateField);

            int result = JOptionPane.showConfirmDialog(null, panel, "Calcular Diferencia de Fechas", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (result == JOptionPane.OK_OPTION) {
                try {
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                    Date startDate = sdf.parse(startDateField.getText());
                    Date endDate = sdf.parse(endDateField.getText());
                    long diff = endDate.getTime() - startDate.getTime();
                    long diffDays = diff / (1000 * 60 * 60 * 24);
                    JOptionPane.showMessageDialog(null, "Diferencia en días: " + diffDays);
                } catch (ParseException e) {
                    JOptionPane.showMessageDialog(null, "Formato de fecha incorrecto.");
                }
            }
        }
    });

    // Acción para "Insertar Fecha"
    insertarFecha.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            dateChooser = new JDateChooser();
            getContentPane().add(dateChooser, java.awt.BorderLayout.CENTER);
            pack();
        }
    });
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaJCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaJCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaJCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaJCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaJCalendar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jColor;
    private javax.swing.JButton jFuente;
    private javax.swing.JLabel jLabelFuente;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JToolBar jToolBar;
    // End of variables declaration//GEN-END:variables
}
